### PR TITLE
Fixes for 3.11

### LINKED ISSUE #1086: Build for Python 3.11
Python 3.11 will be released towards the end of this year ([possibly October](https://peps.python.org/pep-0664/#schedule)). 

There is a release candidate available now (Python 3.11.0rc1, released 2022-08-29), which is expected to be a stable ABI with the final 3.11.0 release. Therefore, it is reasonable to prepare JPype against this now, and potentially make a release containing a Python 3.11 wheel already.

The changelog is available at https://docs.python.org/3.11/whatsnew/3.11.html#id6.

In terms of complexity, it seems that there are a few issues which will likely come up:

 * The [PyFrameObject](https://docs.python.org/3.11/c-api/frame.html#c.PyFrameObject) structure members have been removed from the public C API. This is [used in the exception handling](https://github.com/jpype-project/jpype/blob/82a7658277b36c628ea305ea705cd012d81471dd/native/common/jp_exception.cpp#L524) in JPype
 * [_PyObject_GC_Malloc](https://github.com/jpype-project/jpype/blob/82a7658277b36c628ea305ea705cd012d81471dd/native/python/pyjp_value.cpp#L46) has been removed in https://github.com/python/cpython/commit/8319114feedd2a5b77378bba24eb9fb2689c5033 - since these weren't public API, there is no obvious suggestion for what to use instead.

cc @Thrameos

### PR DESCRIPTION
**Pull request by Thrameos**
Fixes #1086

### CODE REVIEW

**Comment by pelson** [comment]
We still have compile errors:

```
ative/common/jp_exception.cpp: In function ‘PyObject* tb_create(PyObject*, PyObject*, const char*, const char*, int)’:
native/common/jp_exception.cpp:527:9: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘frame’; did you mean ‘cframe’?
  527 |   state.frame = (PyFrameObject*) prev.get();
      |         ^~~~~
      |         cframe
native/common/jp_exception.cpp:530:9: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘frame’; did you mean ‘cframe’?
  530 |   state.frame = NULL;
      |         ^~~~~
      |         cframe
native/common/jp_exception.cpp:540:84: error: invalid use of incomplete type ‘PyFrameObject’ {aka ‘struct _frame’}
  540 |  JPPyObject lasti = JPPyObject::claim(PyLong_FromLong(((PyFrameObject*)frame.get())->f_lasti));
      |                                                                                    ^~
In file included from /opt/_internal/cpython-3.11.0rc1/include/python3.11/Python.h:42,
                 from native/common/jp_exception.cpp:16:
/opt/_internal/cpython-3.11.0rc1/include/python3.11/pytypedefs.h:22:16: note: forward declaration of ‘PyFrameObject’ {aka ‘struct _frame’}
   22 | typedef struct _frame PyFrameObject;
      |                ^~~~~~
error: command '/usr/bin/ccache' failed with exit code 1
```

Perhaps worth enabling CI for Python 3.11 (you might have to use the Python available on the manylinux image, rather than what Azure provide). I note that currently a release of JPype would fail because it would try to build a Python 3.11 wheel (since we glob the Python versions available on manylinux), even though that isn't tested (something we could try to address another time).

**Comment by rapgro** [comment]
> native/common/jp_exception.cpp:527:9: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘frame’; did you mean ‘cframe’?


```
Changes of the [PyThreadState](https://docs.python.org/3.11/c-api/init.html#c.PyThreadState) structure members:

    frame: removed, use [PyThreadState_GetFrame()](https://docs.python.org/3.11/c-api/init.html#c.PyThreadState_GetFrame) (function added to Python 3.9 by [bpo-40429](https://bugs.python.org/issue?@action=redirect&bpo=40429)).
```

see https://docs.python.org/3.11/whatsnew/3.11.html#id6

**Comment by pelson** [comment]
> see https://docs.python.org/3.11/whatsnew/3.11.html#id6

Thanks @rapgro, but the problem is that we are *setting* the frame, not *getting* the frame in this case. I appreciate that this hasn't been public API in any Python version from Python 2.7. Some interesting context on the motivation at https://github.com/jpype-project/jpype/discussions/1071#discussioncomment-2835357.

**Comment by Thrameos** [comment]
@pelson I found the issue with the broken test.   So I have a fully working copy for 3.11.  Now we just need to get the multi version going and we should be good to go.

**Comment by Thrameos** [comment]
@marscher Some background on this.   Python 3.11 removed a number of internal methods that we were using.  These methods were used because the Python API is completely deficient in some areas like handling stack frames or using custom allocators with GC objects.   They are planning replacements for what we need but none of the replacements are in 3.11.  So they gutted the interface we are standing on, and there is no replacement.   Meaning unless I do something drastic we won't support 3.11 at all.

So I had to come up with a few creative kludges.   The biggest danger is these kludges will introduce reference leaks as they are doing things like initializing an object twice and swapping the memory layout.  They are safer in the sense that I managed to get them to use the public API, but in horrible ways (basically creating using side effects of the public implementations).    Hopefully these last until the replacement API is released.

**Comment by marscher** [comment]
> Python 3.11 removed a number of internal methods that we were using. These methods were used because the Python API is completely deficient in some areas like handling stack frames or using custom allocators with GC objects. They are planning replacements for what we need but none of the replacements are in 3.11. So they gutted the interface we are standing on, and there is no replacement. Meaning unless I do something drastic we won't support 3.11 at all.

That's bad news, lets hope that 3.12 will add support for what is needed.
> 
> So I had to come up with a few creative kludges. The biggest danger is these kludges will introduce reference leaks as they are doing things like initializing an object twice and swapping the memory layout. They are safer in the sense that I managed to get them to use the public API, but in horrible ways (basically creating using side effects of the public implementations). Hopefully these last until the replacement API is released.

I wonder how bullet proof our leakage testing is. This could be the time to check and eventually improve this. I know this is hard to achieve, but would safe us lots of troubles some day. 
If we now can compile and run the testsuite on 3.11m, I'd recommend adding it to the testing matrix.

**Comment by Thrameos** [comment]
Our testing matrix checks common leak paths in objects.  This particular spot is on types not general objects, so it only really leaks after the JVM is shutdown which is less of an issue than an object leak.  Thus unless you were adding lots and lots of dynamically allocated types form Java then the leak may be a problem.   But as we always cache types they are never freed in normal situations anyway.

File: native/python/pyjp_value.cpp [hunk 1]
```diff
@@ -43,8 +45,28 @@ PyObject* PyJPValue_alloc(PyTypeObject* type, Py_ssize_t nitems )
 	JP_PY_TRY("PyJPValue_alloc");
 	// Modification from Python to add size elements
 	const size_t size = _PyObject_VAR_SIZE(type, nitems + 1) + sizeof (JPValue);
-	PyObject *obj = (PyType_IS_GC(type)) ? _PyObject_GC_Malloc(size)
-			: (PyObject *) PyObject_MALLOC(size);
+	PyObject *obj = NULL;
+	if (PyType_IS_GC(type))
+	{
+		// Horrible kludge because python lacks an API for allocating a GC type with extra memory
+		// The privor method _PyObject_GC_Alloc is no longer visible, so we are forced to allocate
```
Comment (pelson) [inline native/python/pyjp_value.cpp:52]: privor -> private

File: native/python/pyjp_value.cpp [hunk 2]
```diff
@@ -23,6 +23,8 @@ extern "C"
 {
 #endif
 
+extern PyObject * _PyObject_GC_Malloc(size_t basicsize);
```
Comment (pelson) [inline native/python/pyjp_value.cpp:26]: this isn't required, I believe.

File: native/python/pyjp_value.cpp [hunk 3]
```diff
@@ -43,8 +45,28 @@ PyObject* PyJPValue_alloc(PyTypeObject* type, Py_ssize_t nitems )
 	JP_PY_TRY("PyJPValue_alloc");
 	// Modification from Python to add size elements
 	const size_t size = _PyObject_VAR_SIZE(type, nitems + 1) + sizeof (JPValue);
```
Comment (pelson) [inline native/python/pyjp_value.cpp:47]: Use of ``_PyObject_VAR_SIZE`` here looks like it could be a future candidate for breaking change. (cc @vstinner in light of the comment in https://bugs.python.org/msg411999)

File: jpype/_jvmfinder.py [hunk 4]
```diff
@@ -320,10 +320,10 @@ def _javahome_binary(self):
         """
         import platform
         import subprocess
-        from distutils.version import StrictVersion
+        from packaging.version import Version
 
-        current = StrictVersion(platform.mac_ver()[0][:4])
-        if current >= StrictVersion('10.6') and current < StrictVersion('10.9'):
+        current = Version(platform.mac_ver()[0][:4])
+        if current >= Version('10.6') and current < Version('10.9'):
```
Comment (pelson) [inline jpype/_jvmfinder.py:326]: I guess this is part of your distutils handling. I suggest that this can be a separate PR, or alternatively, you should add ``packaging`` as an explicit dependency.

File: native/common/jp_exception.cpp [hunk 5]
```diff
@@ -489,79 +489,57 @@ void JPypeException::toJava(JPContext *context)
...
-	PyFrameObject *frame = PyFrame_New(&state, code, dict, NULL);
-	
-	// frame just borrows the reference rather than claiming it
-	// so we need to get rid of the extra reference here.
-	Py_DECREF(code);
+	PyThreadState *state = PyThreadState_GET();
+	PyFrameObject *pframe = PyFrame_New(state, (PyCodeObject*) code.get(), dict, NULL);
+	JPPyObject frame = JPPyObject::accept((PyObject*)pframe);
+
+	// Swap the back pointer
```
Comment (pelson) [inline native/common/jp_exception.cpp:511]: Commented code can now be removed?

File: setupext/test_java.py [hunk 6]
```diff
@@ -53,7 +53,7 @@ def compileJava():
     srcs = glob.glob('test/harness/jpype/**/*.java', recursive=True)
     srcs.extend(glob.glob('test/harness/org/**/*.java', recursive=True))
     exports = ""
-    if version > 7:
+    if version == 8:
```
Comment (pelson) [inline setupext/test_java.py:56]: Looks correct, but unrelated.

**Review by pelson — COMMENTED** [review]
I added a few change proposals in https://github.com/Thrameos/jpype/pull/56.

In general: I propose that this is merged, and that we have a special ``v1.4.0.post0`` Python3.11 wheel be uploaded to PyPI before the 2022-10-24 (Python 3.11 release day).

File: native/python/pyjp_value.cpp (hunk 3 above)
Comment (Thrameos) [reply native/python/pyjp_value.cpp:47]: There was nothing pulbic with tge same functionality.  We could copy it into our code if needed.

File: jpype/_jvmfinder.py (hunk 4 above)
Comment (Thrameos) [reply jpype/_jvmfinder.py:326]: Okay.  This was required to get Python 3.11 to work for me so I think it is same theme.  I will look at dependencies.

File: setupext/test_java.py (hunk 6 above)
Comment (Thrameos) [reply setupext/test_java.py:56]: It was an old bug that cropped up because when I did a full clean there are two copies of a file.  One for java 8 and one for 9.   I can make another PR but it seem like a lot of work to maje that change seperately then .merge it back.

File: jpype/_jvmfinder.py (hunk 4 above)
Comment (Thrameos) [reply jpype/_jvmfinder.py:326]: Hmm.  I dont see where it goes in setup.py.  we never listed distutils as a requirement.  Can you suggest the required line.

File: native/python/pyjp_value.cpp (hunk 2 above)
Comment (Thrameos) [reply native/python/pyjp_value.cpp:26]: Left over fron early attempt.  Removed.

File: native/python/pyjp_value.cpp (hunk 1 above)
Comment (Thrameos) [reply native/python/pyjp_value.cpp:52]: Fixed.

File: setupext/test_java.py (hunk 6 above)
Comment (Thrameos) [reply setupext/test_java.py:56]: I keep hoping Java 8 will retire as it has a some reflection differences.  But it wont retire until 2026!

File: jpype/_jvmfinder.py (hunk 4 above)
Comment (pelson) [reply jpype/_jvmfinder.py:326]: Sure. It is install_requires https://github.com/jpype-project/jpype/blob/master/setup.py#L81.

**Review by pelson — APPROVED** [review]
The minor point about adding ``packaging`` as a dependency aside, looks good to me. Much better than what was there before in fact. Excellent work @Thrameos!

File: jpype/_jvmfinder.py (hunk 4 above)
Comment (Thrameos) [reply jpype/_jvmfinder.py:326]: I guess it was supposed to have distutils there before.   

https://packaging.python.org/en/latest/discussions/install-requires-vs-requirements/

I don't see the same format we have so I am guessing we want...

```  python
install_requires=['typing_extensions ; python_version< "3.8"',
        'packaging ; python_version< "3.10"'],
```

Comment (marscher) [reply jpype/_jvmfinder.py:326]: distutils is a standard library, which has been deprecated for a while now and will be removed in Python 3.12.

Comment (pelson) [reply jpype/_jvmfinder.py:326]:
```
'packaging ; python_version< "3.10"'
```

Should just be

```
'packaging'
```

**Comment by pelson** [comment]
@Thrameos & @marscher - I'm unavailable for a bit now, and won't be back before the Python 3.11 release. Do you agree that we should merge and release a ``v1.4.0.post0`` wheel, with only a Python 3.11 build? I believe this should work out just fine for existing users, and new Python 3.11 users will get the newer version.

**Comment by marscher** [comment]
I'm also fine with a micro patch release for this kind of change. Sorry for the delay!

**Comment by Thrameos** [comment]
Will do.  Thanks.

**Comment by vstinner** [comment]
native/python/pyjp_value.cpp:

```
		// Horrible kludge because python lacks an API for allocating a GC type with extra memory
		// The private method _PyObject_GC_Alloc is no longer visible, so we are forced to allocate
		// a different type with the extra memory and then hot swap the type to the real one.
```

FYI @encukou is working on a Python API for that.

**Comment by Thrameos** [comment]
Yep.  Have looked at that API, but it doesn't exist for Py 3.11 so we are stuck because our old method using private functions doesn't work.   Worse it appears this kludge may break something in the garbage collector at least in one projects testing.   So I need to investigate further this weekend.

**Comment by marscher** [comment]
Thanks for taking the shot!

Should we try to pin JPype to use Python<3.11 in the meantime, if we run into such horrible subtle errors like garbage collection issues?

**Comment by pelson** [comment]
> Thanks for taking the shot!
> 
> Should we try to pin JPype to use Python<3.11 in the meantime, if we run into such horrible subtle errors like garbage collection issues?

IMO, if we can engage with the Python RC process, there should be enough time to avoid nasty surprises. If we find that we absolutely can't be compatible with Python 3.12, we can always release something then which has that constraint. In general, upper pins are discouraged ([long read](https://iscinumpy.dev/post/bound-version-constraints/)).

I think some more dialogue between the C API team and JPype should come out of this :crossed_fingers:, so I truly hope things will get better, not worse, in the future.

**Comment by marscher** [comment]
A first step could be testing against unreleased versions of Python, right? I'm sure they provide a nightly build, which we can integrate into our CI process on a regular basis.

@pelson Thanks for the reference about version pinning. I wasn't aware, that is becoming a disease in the eco system :)
How do you suggest to get in touch with the C-API team? If the nightly Python job fails, we could get in touch like on their bug-tracker or IRC, whatever they use nowadays.

**Comment by encukou** [comment]
The first Alpha of CPython 3.12 is already out. I think the alphas/betas would work bit better for you than nightly builds, since they're proper releases that pass the full test suite (i.e. stable buildbots) & have release blockers sorted out.

There's no formal “C API” team, but to get in touch with the relevant people, use the `expert-C-API` label on the CPython bug tracker, or the just-opened C-API category on Discourse: https://discuss.python.org/c/core-dev/c-api/30

**Comment by marscher** [comment]
Thanks a lot @encukou for these useful hints!
