### PR TITLE
Fix for classes with no canonical name

### LINKED ISSUE #841: SIGSEGV when importing scala.collection.Iterator$Leading$1
JPype version: 23f3c95180c35ed3c7cb2f6a59bac4aa5b493b0d

`scala/focal,focal,now 2.11.12-4 all [installed]`

```python
import jpype
from pathlib import Path
scalaPath = Path("/usr/share/scala-2.11/lib")
jpype.startJVM(classpath=[str(scalaPath / "scala-library.jar")])
jpype.JClass("scala.collection.Iterator$Leading$1")
```

```
A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f21fe1f9b94, pid=1316593, tid=1316593
#
# JRE version: OpenJDK Runtime Environment (14.0.1+7) (build 14.0.1+7-Ubuntu-1ubuntu1)
# Java VM: OpenJDK 64-Bit Server VM (14.0.1+7-Ubuntu-1ubuntu1, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0x25cb94]

Current thread (0x0000000002f91000):  JavaThread "main" [_thread_in_vm, id=1316593, stack(0x00007ffc842d3000,0x00007ffc843d3000)]

Stack: [0x00007ffc842d3000,0x00007ffc843d3000],  sp=0x00007ffc843cb488,  free space=993k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0x25cb94]
C  [_jpype.cpython-38-x86_64-linux-gnu.so+0x5dcbb]  JPJavaFrame::GetStringUTFChars(_jstring*, unsigned char*)+0x1b

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  org.jpype.manager.TypeFactoryNative.defineObjectClass(JLjava/lang/Class;Ljava/lang/String;J[JI)J+0
j  org.jpype.manager.TypeManager.createOrdinaryClass(Ljava/lang/Class;ZZ)Lorg/jpype/manager/ClassDescriptor;+304
J 368 c1 org.jpype.manager.TypeManager.getClass(Ljava/lang/Class;)Lorg/jpype/manager/ClassDescriptor; (31 bytes) @ 0x00007f21e02a8f4c [0x00007f21e02a8b80+0x00000000000003cc]
j  org.jpype.manager.TypeManager.findClass(Ljava/lang/Class;)J+106
j  org.jpype.manager.TypeManager.findClassByName(Ljava/lang/String;)J+14
v  ~StubRoutines::call_stub
```

<details>
<summary> Also these classes cause crashes:</summary>

```python
sc = "scala."
scc = sc + "collection."
scrf = sc + "reflect."
scrfi = scrf + "internal."
scrfo = scrf + "io."
sct = sc + "tools."
sctn = sct + "nsc."
sctnbj = sctn + "backend.jvm."
sctnc = sctn + "typechecker."
sctnt = sctn + "transform."
sctntp = sctnt + "patmat."
sctni = sctn + "interpreter."
scrfit = scrfi + "tpe."
scrfm = scrf + "macros."
scrfmc = scrfm + "contexts."

blackList = {
	scc + "Iterator$Leading$1",
	scc + "Iterator$PartitionIterator$1",
	scc + "Iterator$Partner$1",
	scc + "parallel.mutable.ParHashMapCombiner$table$2$",
	scrfi + "ExistentialsAndSkolems$$anonfun$packSymbols$1",
	scrfi + "ExistentialsAndSkolems$Deskolemizer$1",
	scrfi + "Internals$SymbolTableInternal$changeOwnerAndModuleClassTraverser$2$",
	scrfit + "TypeMaps$InstantiateDependentMap$StabilizedArgTp$",
	scrfit + "TypeMaps$InstantiateDependentMap$StableArgTp$",
	scrfit + "TypeMaps$InstantiateDependentMap$UnstableArgTp$",
	scrfit + "TypeMaps$InstantiateDependentMap$treeTrans$2$",
	scrfit + "TypeMaps$SubstSymMap$mapTreeSymbols$$anonfun$transform$2",
	scrfit + "TypeMaps$SubstSymMap$mapTreeSymbols$$anonfun$transform$1",
	scrfit + "TypeMaps$SubstTypeMap",
	scrfit + "TypeMaps$SubstTypeMap$trans$2$",
	scc + "immutable.ChampBaseIterator",
	scrfo + "FileZipArchive$FileEntry$1",
	scrfo + "JavaToolsPlatformArchive$$anonfun$iterator$2$FileEntry$4",
	scrfo + "ManifestResources$$anonfun$iterator$1$FileEntry$3",
	scrfo + "URLZipArchive$EmptyFileEntry$1",
	scrfo + "URLZipArchive$FileEntry$2",
	scrfm + "compiler.Validators$Validator$SigGenerator$2$",
	scrfm + "compiler.Validators$Validator$SigGenerator$2$SigmaTypeMap$",
	scrfmc + "Internals$$anon$1$HofTransformer",
	scrfmc + "Internals$$anon$1$HofTypingTransformer",
	scrfmc + "Reifiers$utils$2$",
	sctn + "Global$ClassPathOrdering$2$",
	sctnbj + "GenASM$JPlainBuilder$$anonfun$isClosureApply$1$1",
	sctnbj + "GenASM$JPlainBuilder$Interval$3",
	sctnbj + "GenASM$JPlainBuilder$Interval$4$",
	sctnbj + "GenASM$JPlainBuilder$LineNumberEntry$3",
	sctnbj + "GenASM$JPlainBuilder$LineNumberEntry$4$",
	sctnbj + "GenASM$JPlainBuilder$LocVarEntry$3",
	sctnbj + "GenASM$JPlainBuilder$LocVarEntry$4$",
	sctnbj + "GenASM$JPlainBuilder$scoping$2$",
	sctnbj + "opt.CallGraph$CallsiteInfo$3",
	sctnbj + "opt.CallGraph$CallsiteInfo$4$",
	sctnbj + "opt.ClosureOptimizer$closureInitOrdering$2$",
	sctn + "doc.model.IndexModelFactory$$anon$1$result$2$",
	sctn + "doc.model.ModelFactory$EntityImpl$$anonfun$annotations$1$$typecreator1$1",
	sctn + "interactive.REPL$compiler$2$",
	sctni + "IMain$$typecreator2$1",
	sctni + "Imports$ReqAndHandler$3",
	sctni + "Imports$ReqAndHandler$4$",
	sctni + "ReplVals$AppliedTypeFromTags$1",
	sctn + "symtab.BrowsingLoaders$BrowserTraverser$1",
	sctnt + "Constructors$OmittablesHelper$detectUsages$2$",
	sctnt + "Mixin$MixinTransformer$AddInitBitsTransformer$1",
	sctnt + "Mixin$MixinTransformer$AddInitBitsTransformer$1$$anonfun$transformStats$1",
	sctnt + "Mixin$MixinTransformer$TreeSymSubstituterWithCopying$1",
	sctnt + "Mixin$SingleUseTraverser$2$",
	sctnt + "SpecializeTypes$$anon$2$CollectMethodBodies",
	sctnt + "SpecializeTypes$FullTypeMap$1",
	sctntp + "Interface$TypedSubstitution$Substitution$substIdentsForTrees$2$",
	sctntp + "Logic$PropositionalLogic$gatherEqualities$2$",
	sctntp + "Logic$PropositionalLogic$rewriteEqualsToProp$2$",
	sctntp + "MatchAnalysis$MatchAnalyzer$VariableAssignment$3",
	sctntp + "MatchAnalysis$MatchAnalyzer$VariableAssignment$3$$anonfun$uniqueEqualTo$1$$anonfun$apply$20",
	sctntp + "MatchAnalysis$MatchAnalyzer$VariableAssignment$4$",
	sctntp + "MatchApproximation$MatchApproximator$TreeMakersToProps$TreeMakerToProp$condStrategy$2$",
	sctntp + "MatchTranslation$MatchTranslator$ExtractorCallRegular",
	sctntp + "MatchTranslation$MatchTranslator$ExtractorCallRegular$splice$2$",
	sctntp + "ScalaLogic$TreesAndTypesDomain$Var$ExcludedPair$2",
	sctntp + "ScalaLogic$TreesAndTypesDomain$Var$ExcludedPair$3$",
	sctntp + "Solving$Solver$TseitinSolution$3",
	sctntp + "Solving$Solver$TseitinSolution$4$",
	sctntp + "TreeAndTypeAnalysis$CheckableTreeAndTypeAnalysis$typeArgsToWildcardsExceptArray$2$",
	sctnc + "Implicits$ImplicitSearch$ImplicitComputation$LocalShadower$1",
	sctnc + "Implicits$ImplicitSearch$ImplicitComputation$LocalShadower$1",
	sctnc + "Implicits$ImplicitSearch$ImplicitComputation$NoShadower$2$",
	sctnc + "Infer$Inferencer$InferMethodAlternativeTwice$1",
	sctnc + "Infer$Inferencer$InferTwice$1",
	sctnc + "Macros$UnsigmaTypeMap$2$",
	sctnc + "RefChecks$RefCheckTransformer$LevelInfo",
	sctnc + "RefChecks$RefCheckTransformer$MixinOverrideError$3",
	sctnc + "RefChecks$RefCheckTransformer$MixinOverrideError$4$",
	sctnc + "Typers$Typer$ArrayInstantiation$2$",
	sctnc + "Typers$Typer$checkEphemeralDeep$2$",
	sct + "reflect.FormatInterpolator$$typecreator1$1",
}
```

</details>

### PR DESCRIPTION
**Pull request by Thrameos**
Fixes #841

### CODE REVIEW

**Comment by Thrameos** [comment]
This one should likely get a test but I didn't have time to figure out how to create a class without a canonical name.   Most likely it is by creating anonymous classes.   I am not sure why exactly we would need a specific anonymous class creation though as usually the parent class is sufficient to get all of the behaviors of the derived class.

File: native/java/org/jpype/manager/TypeManager.java [hunk 1]
```diff
@@ -445,6 +445,8 @@ private ClassDescriptor createOrdinaryClass(Class<?> cls, boolean special, boole
 
     // FIXME watch out for anonyous and lambda here.
```
Comment (marscher) [inline native/java/org/jpype/manager/TypeManager.java:446]: I think you can now remove the FIXME (anonymous, or inner classes), right?

**Review by marscher — APPROVED** [review]
Thanks for the quick fix! LGTM

File: native/java/org/jpype/manager/TypeManager.java (hunk 1 above)
Comment (marscher) [reply native/java/org/jpype/manager/TypeManager.java:446]: Would it be possible to handle lambdas in this PR as well?

Comment (Thrameos) [reply native/java/org/jpype/manager/TypeManager.java:446]: I think that anonymous and  inner classes don't normally make it to this location.   It was only a manually requested class that got here.   I will work to confirm and remove the FIXME in another PR once I have my development machine back.

Comment (marscher) [reply native/java/org/jpype/manager/TypeManager.java:446]: Ah you are still suffering - that's unfortunate. What is going on with your IT-department to take so long to fix a single laptop?

Comment (Thrameos) [reply native/java/org/jpype/manager/TypeManager.java:446]: The central government agency imposes security requirements on all computer images, and if that central image and all the different levels of group policies has a problem on a particular brand of laptops or such then unfortunately it takes a while to figure out which level of the IT is sending the bad configuration (central. department, or group).   I once lost 4 months on my primary computing server because of a problem with IT installing 4 separate copies of the backup server (without uninstalling the previous versions) and basically leaving my primary machine nonfunctional leaving 2 CPUs with 8 cores and the disk controller pegged 24-7.  

With 20k computers, the thought of one having a problem (or admitting that a central requirement has an issue) is at times challenging.   I am guessing that many people just don't notice their computer is dog slow and just put up with it (hence the perception everything is working fine).  I don't blame the local team as 90% of the time it isn't coming from them.  For example, the laptop came supplied with drivers and such from Dell, it was then reimaged to drivers and windows from 12 months ago.   Central are still evaluating the windows from 9 months ago, and that should be installed next month, at which time they will start evaluating the next version.  Yes, they backport all security fixes so we are bleeding edge on that front, but the actual image is always very out of date.  Real fun starts when their backport patch fails and the whole site as buggy or broken images for a month.   I can't imagine what life is like in our IT department, but  I would wager it is demoralizing at best.
